### ISSUE TITLE
help or command line parameters missing

### ISSUE THREAD

**Issue by Stingra-VI** [microsoft/AttackSurfaceAnalyzer#234]
Sorry, maybe I am totally off, but - I have been searching for any parameters to run the ASA with command line parameters (potentially with the deployment solution) before any changes (applications, etc.) are submitted.

I have seen the screenshots with the command line parameters at the:
https://www.microsoft.com/security/blog/2019/05/15/announcing-new-attack-surface-analyzer-2-0/

I have tried to use the Slim and the Full package.

I have tried the Slim package:
I is just starting the application for the browser-session on localhost:5000.

_then I have tried the Full-Version using the CMD:_
"Attack Surface Analyzer.exe" /?

**All I get is:**
 Electron Socket IO Port: 8000
Electron Socket started on port 8000 at 127.0.0.1
ASP.NET Core Port: 8000
stdout: Use Electron Port: 8000

stdout: crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://127.0.0.1:8000: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

ASP.NET Core Application connected... global.electronsocket I9Es-Tw_xj3gYtdZAAAA 2019-06-13T08:11:59.758Z

Windows 10 Enterprise:
Microsoft Windows [Version 10.0.16299.1146]

ASA:
AsaGui-slim-win10-2.0.153

Also, I was searching here in the WIKI for any parameters. Please assist.
Thank you very much.

**Comment by gfs** [comment]
Please try the "AsaCli" releases for the command line interface.

[Here](https://github.com/microsoft/AttackSurfaceAnalyzer/releases/download/v2.0.154%2B303aa9fef5/AsaCli-win-2.0.154.zip) is the current version for windows.
