### ISSUE TITLE
The open port and service collectors in Ubuntu Linux fail

### ISSUE THREAD

**Issue by cmesyngier** [microsoft/AttackSurfaceAnalyzer#255]
[Dockerfile.txt](https://github.com/microsoft/AttackSurfaceAnalyzer/files/3507453/Dockerfile.txt)

**Describe the bug**
Running ASA in a container based on dotnet core 2.2 Ubuntu fails on the open port and service collectors

**To Reproduce**
1. Download the attached file
2. Build the container image using (run on the directory where the file was downloaded)
```
docker build -t linux-asa -f Dockerfile.txt .
```
3. Observe on step 12/13 the failure after starting the OpenPortCollector

**Expected behavior**
No errors should be encounter when running the openportcollector or servicecollector

**Screenshots**
Begin OpenPortCollector.
[22:55:40 ERR] Error collecting from OpenPortCollector: No such file or directory    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String command, String[] args) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 24
   at AttackSurfaceAnalyzer.Collectors.OpenPorts.OpenPortCollector.ExecuteLinux() in /home/vsts/work/1/s/Lib/Collectors/OpenPorts/OpenPortCollector.cs:line 174
   at AttackSurfaceAnalyzer.Collectors.OpenPorts.OpenPortCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/OpenPorts/OpenPortCollector.cs:line 108
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Cli/Program.cs:line 1332
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String command, String[] args) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 24
   at AttackSurfaceAnalyzer.Collectors.OpenPorts.OpenPortCollector.ExecuteLinux() in /home/vsts/work/1/s/Lib/Collectors/OpenPorts/OpenPortCollector.cs:line 174
   at AttackSurfaceAnalyzer.Collectors.OpenPorts.OpenPortCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/OpenPorts/OpenPortCollector.cs:line 108
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Cli/Program.cs:line 1332
[22:55:40 INF] Begin ServiceCollector.
[22:55:40 ERR] Error collecting from ServiceCollector: No such file or directory    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String command, String[] args) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 24
   at AttackSurfaceAnalyzer.Collectors.Service.ServiceCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/Service/ServiceCollector.cs:line 169
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Cli/Program.cs:line 1332
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String command, String[] args) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 24
   at AttackSurfaceAnalyzer.Collectors.Service.ServiceCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/Service/ServiceCollector.cs:line 169
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Cli/Program.cs:line 1332

**System Configuration (please complete the following information):**
 - OS: Windows host
 - OS Version: Windows 10 1803 host, Docker Desktop using Linux containers
 - Application Version: 2.0.154
 - CLI or GUI: cli

**Comment by gfs** [comment]
Thanks for your report and for the Dockerfile. 

I checked out the line and it looks like this is failing trying to run ```ss -ln```.

**Comment by cmesyngier** [comment]
I tried installing the iproute2 package that comes with the ss utility and that fixed the OpenPortCollector issue.

The ServiceCollector is still failing, maybe another package needs to be installed? This is the error stack:

> ERR] Error collecting from ServiceCollector: No such file or directory    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String command, String[] args) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 24
>    at AttackSurfaceAnalyzer.Collectors.Service.ServiceCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/Service/ServiceCollector.cs:line 169
>    at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Cli/Program.cs:line 1332
> System.ComponentModel.Win32Exception (2): No such file or directory
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String command, String[] args) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 24
>    at AttackSurfaceAnalyzer.Collectors.Service.ServiceCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/Service/ServiceCollector.cs:line 169
>    at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Cli/Program.cs:line 1332

**Comment by gfs** [comment]
The service collector depends on ```systemctl```.  Can you try getting the package for that?

Will look into prompting user to install these packages (with optional silent) for 2.1.

**Comment by cmesyngier** [comment]
I guess systemd is not installed by default in this version of Ubuntu (18.04). After installing it all collectors succeed!

**Comment by gfs** [comment]
Awesome!
