### ISSUE TITLE
AsaCli.exe crash during first scan of updated master

### ISSUE THREAD

**Issue by exquirentibus** [microsoft/AttackSurfaceAnalyzer#266]
Updated VS 2019 Preview to latest version today, but did Not update an NuGets

Pulled the latest master branch using GitHub in VS 2019.

I did a clean then build, then dotnet publish -c Release -r win10-x64

cd to CLI\bin\Release\netcoreapp2.2\win10-x64 

from an Admin PowerShell set to the G:\Git Source\ASA\Cli\bin\Release\netcoreapp2.2\win10-x64 folder:

.\asacli.exe collect --all --runid 1stScan

and the result was:

 PS G:\Git Source\ASA\Cli\bin\Release\netcoreapp2.2\win10-x64> .\asacli.exe collect --all --runid 1stScan
[20:12:30 INF] AttackSurfaceAnalyzerCli v.2.1.52-alpha+ee81cc87b5
[20:12:31 INF] This application collects usage data to help us improve Attack Surface Analyzer.
[20:12:31 INF] For our privacy policy visit: https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/master/PRIVACY.md.
[20:12:31 INF] To disable telemetry run 'AttackSurfaceAnalyzerCli.exe config --telemetry-opt-out true'.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector..ctor(String runId, Boolean enableHashing, String directories, Boolean downloadCloud, Boolean examineCertificates) in G:\Git Source\ASA\Lib\Collectors\FileSystemCollector.cs:line 40
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.RunCollectCommand(CollectCommandOptions opts) in G:\Git Source\ASA\Cli\Program.cs:line 1192
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerCLI.Main(String[] args) in G:\Git Source\ASA\Cli\Program.cs:line 257

**Comment by gfs** [comment]
Sorry about that.  I've fixed this issue and master is now usable.  Please test against the master branch now.

**Comment by exquirentibus** [comment]
Yes, that fixed the crash!!  Thanks!!

And this time the 2nd scan took the same amount of time as the first scan, and the json showed my registry and file changes!!!   Excellent!!

One thing I've noticed during my short time using GitHub - when I pulled the master, ALL the files had the same date.

I know it's possible to change the modification date on any file (Directory Opus will do that), and it's very useful to be able to see the age of a file.

I know it does change the date when I fetch my changes, but even that date is wrong as it's the timestamp of the fetch, not the timestamp of the file's modification date from the GitHub repository.

I'd like the VS GitHub tool to modify the dates to match the master dates in the GitHub Repository when initially grabbing the repository and when fetching changes from the repository.

How would I propose this possible 'enhancement' to the GitHub VS2019 development team?   Thanks!!

**Comment by gfs** [comment]
If it is working it doesn't look like you need to update anything :).

Git [doesn't keep track](https://confluence.atlassian.com/bbkb/preserving-file-timestamps-with-git-and-mercurial-781386524.html) of file modification times, so there's no way for it to bring the timestamps over to your system.
