### ISSUE TITLE
error at file collector on Windows 8 1809

### ISSUE THREAD

**Issue by rzcrjz** [microsoft/AttackSurfaceAnalyzer#300]
got following crash when running the file system collector.

version used => v. 2.1.29-beta+c0b3adbc7a

[14:43:36 ERR] Error collecting from One or more errors occurred. (Could not find file 'C:\Windows\System32\Tasks_Migrated\Microsoft\Office\Configuration Manager\Configuration Manager OfficeC2RClient Task'.):    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.ExecuteInternal() in D:\a\1\s\Lib\Collectors\FileSystemCollector.cs:line 89
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute() in D:\a\1\s\Lib\Collectors\BaseCollector.cs:line 36
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(CollectCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 1351 {3}
System.AggregateException: One or more errors occurred. (Could not find file 'C:\Windows\System32\Tasks_Migrated\Microsoft\Office\Configuration Manager\Configuration Manager OfficeC2RClient Task'.)
 ---> System.IO.FileNotFoundException: Could not find file 'C:\Windows\System32\Tasks_Migrated\Microsoft\Office\Configuration Manager\Configuration Manager OfficeC2RClient Task'.
File name: 'C:\Windows\System32\Tasks_Migrated\Microsoft\Office\Configuration Manager\Configuration Manager OfficeC2RClient Task'
   at System.IO.FileInfo.get_Length()
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.FileSystemInfoToFileSystemObject(FileSystemInfo fileInfo, Boolean downloadCloud, Boolean INCLUDE_CONTENT_HASH) in D:\a\1\s\Lib\Collectors\FileSystemCollector.cs:line 297
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.<ExecuteInternal>b__7_0(FileSystemInfo fileInfo) in D:\a\1\s\Lib\Collectors\FileSystemCollector.cs:line 128
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.ExecuteInternal() in D:\a\1\s\Lib\Collectors\FileSystemCollector.cs:line 89
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute() in D:\a\1\s\Lib\Collectors\BaseCollector.cs:line 36
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(CollectCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 1351

**Comment by gfs** [comment]
Thanks for the report.  I'll have a fix out today.
