### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added. Key: UNKNOWN

### ISSUE THREAD

**Issue by exquirentibus** [microsoft/AttackSurfaceAnalyzer#302]
Running on fully patched Win10 box I got an unhandled exception during the export-collect phase.   I added one text file to G: drive before I generated the 2nd scan.

Here are my PowerShell outputs while running as an administrator:

`PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.29-beta\res> .\asa.exe collect --all --runid 1stScan
[19:06:18 INF] AttackSurfaceAnalyzer v.2.1.29-beta+c0b3adbc7a
[19:06:18 INF] This application collects usage data to help us improve Attack Surface Analyzer.
[19:06:18 INF] For our privacy policy visit: https://github.com/Microsoft/AttackSurfaceAnalyzer/blob/master/PRIVACY.md.
[19:06:18 INF] To disable telemetry run 'AttackSurfaceAnalyzerCli.exe config --telemetry-opt-out true'.
[19:06:18 INF] Loaded filters: Embedded
[19:06:18 INF] Begin 1stScan.
[19:06:18 INF] Starting 9 Collectors.
[19:06:18 INF] Starting FileSystemCollector.
[19:06:18 INF] Scanning root C:\
[19:09:02 INF] Scanning root G:\
[19:09:58 INF] Scanning root H:\
[19:13:32 INF] Completed FileSystemCollector in 00h:07m:13s:604ms.
[19:13:32 INF] Starting OpenPortCollector.
[19:13:32 INF] Completed OpenPortCollector in 00h:00m:00s:493ms.
[19:13:32 INF] Starting ServiceCollector.
[19:13:33 INF] Completed ServiceCollector in 00h:00m:00s:590ms.
[19:13:33 INF] Starting UserAccountCollector.
[19:13:34 INF] Completed UserAccountCollector in 00h:00m:01s:434ms.
[19:13:34 INF] Starting RegistryCollector.
[19:18:44 INF] Completed RegistryCollector in 00h:05m:10s:002ms.
[19:18:44 INF] Starting CertificateCollector.
[19:18:45 INF] Completed CertificateCollector in 00h:00m:00s:508ms.
[19:18:45 INF] Starting FirewallCollector.
[19:18:46 INF] Completed FirewallCollector in 00h:00m:00s:672ms.
[19:18:46 INF] Starting ComObjectCollector.
[19:18:54 INF] Completed ComObjectCollector in 00h:00m:08s:283ms.
[19:18:54 INF] Starting EventLogCollector.
[19:18:59 INF] Completed EventLogCollector in 00h:00m:05s:082ms.
PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.29-beta\res>  To disable telemetry run 'AttackSurfaceAnalyzerCli.exe config --telemetry-opt-out true'.

-----------------
PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.29-beta\res> .\asa.exe collect --all --runid 2ndScan
[21:47:55 INF] AttackSurfaceAnalyzer v.2.1.29-beta+c0b3adbc7a
[21:47:55 INF] Loaded filters: Embedded
[21:47:55 INF] Begin 2ndScan.
[21:47:55 INF] Starting 9 Collectors.
[21:47:55 INF] Starting FileSystemCollector.
[21:47:56 INF] Scanning root C:\
[21:50:04 INF] Scanning root G:\
[21:50:56 INF] Scanning root H:\
[21:54:07 INF] Completed FileSystemCollector in 00h:06m:11s:549ms.
[21:54:07 INF] Starting OpenPortCollector.
[21:54:07 INF] Completed OpenPortCollector in 00h:00m:00s:412ms.
[21:54:07 INF] Starting ServiceCollector.
[21:54:08 INF] Completed ServiceCollector in 00h:00m:00s:644ms.
[21:54:08 INF] Starting UserAccountCollector.
[21:54:10 INF] Completed UserAccountCollector in 00h:00m:01s:528ms.
[21:54:10 INF] Starting RegistryCollector.
[21:59:17 INF] Completed RegistryCollector in 00h:05m:07s:149ms.
[21:59:17 INF] Starting CertificateCollector.
[21:59:17 INF] Completed CertificateCollector in 00h:00m:00s:518ms.
[21:59:17 INF] Starting FirewallCollector.
[21:59:18 INF] Completed FirewallCollector in 00h:00m:00s:638ms.
[21:59:18 INF] Starting ComObjectCollector.
[21:59:26 INF] Completed ComObjectCollector in 00h:00m:08s:172ms.
[21:59:26 INF] Starting EventLogCollector.
[21:59:31 INF] Completed EventLogCollector in 00h:00m:04s:965ms.
PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.29-beta\res>

------------
PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.29-beta\res> .\asa.exe export-collect
[22:08:44 INF] AttackSurfaceAnalyzer v.2.1.29-beta+c0b3adbc7a
[22:08:44 INF] Comparing 1stScan vs 2ndScan.
[22:09:00 INF] Completed Comparing in 00h:00m:15s:634ms.
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: UNKNOWN
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AttackSurfaceAnalyzer.Utils.Analyzer..ctor(PLATFORM platform, String filterLocation) in D:\a\1\s\Lib\Utils\Analyzer.cs:line 35
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.CompareRuns(CompareCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 1034
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunExportCollectCommand(ExportCollectCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 518
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.<>c.<Main>b__7_2(ExportCollectCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 288
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 notParsedFunc)
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.Main(String[] args) in D:\a\1\s\Asa\Program.cs:line 284
PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.29-beta\res>
`

**Comment by gfs** [comment]
Thank you for the report.  I am investigating now.
