### ISSUE TITLE
InvalidOperationException on export-collect

### ISSUE THREAD

**Issue by scovetta** [Microsoft/AttackSurfaceAnalyzer#31]
**Describe the bug**
If you run export-collect without any options, you get an InvalidOperationException:

```
PS C:\Users\scovetta\Desktop\AttackSurfaceAnalyzerCli-windows-2.0.38-beta+6b0ad9732a> .\AttackSurfaceAnalyzerCli.exe export-collect /?
2019-04-01 05:25:14.5075|INFO|AttackSurfaceAnalyzer.Utils.Logger|AttackSurfaceAnalyzerCli v.2.0.38-beta+6b0ad9732a
2019-04-01 05:25:14.7827|WARN|AttackSurfaceAnalyzer.Utils.Logger|Done setting up.

Unhandled Exception: System.InvalidOperationException: Value must be set.
   at Microsoft.Data.Sqlite.SqliteParameter.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteParameterCollection.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerCLI.RunExportCollectCommand(ExportCollectCommandOptions opts) in D:\a\1\s\Cli\Program.cs:line 213
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerCLI.Main(String[] args) in D:\a\1\s\Cli\Program.cs:line 208
```

**To Reproduce**
1. Run `AttackSurfaceAnalyzerCli.exe export-collect`
2. See error.

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - Application Version: 2.0.38-beta+6b0ad9732a
 - CLI or GUI: CLI

**Comment by gfs** [comment]
Fixed.
