### ISSUE TITLE
ArgumentNullException for Asa-win-2.1.30-beta

### ISSUE THREAD

**Issue by exquirentibus** [microsoft/AttackSurfaceAnalyzer#310]
Running on Win10-64.  I'll include all my commands and the output showing the error:

.\asa.exe config --telemetry-opt-out true
.\asa.exe collect --all --runid 1stScan
.\asa.exe collect --all --runid 2ndScan

PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.30-beta\res> .\asa.exe collect --all --runid 2ndScan
[14:54:24 INF] AttackSurfaceAnalyzer v.2.1.30-beta+2c1f3fdf10
[14:54:24 INF] Loaded filters: Embedded
[14:54:24 INF] Begin 2ndScan.
[14:54:24 INF] Starting 9 Collectors.
[14:54:24 INF] Starting FileSystemCollector.
[14:54:24 INF] Scanning root C:\
[14:58:26 INF] Scanning root G:\
[14:59:18 INF] Scanning root H:\
[15:02:09 INF] Completed FileSystemCollector in 00h:07m:45s:060ms.
[15:02:09 INF] Starting OpenPortCollector.
[15:02:10 INF] Completed OpenPortCollector in 00h:00m:00s:485ms.
[15:02:10 INF] Starting ServiceCollector.
[15:02:10 INF] Completed ServiceCollector in 00h:00m:00s:602ms.
[15:02:10 INF] Starting UserAccountCollector.
[15:02:12 INF] Completed UserAccountCollector in 00h:00m:01s:972ms.
[15:02:12 INF] Starting RegistryCollector.
[15:09:09 INF] Completed RegistryCollector in 00h:06m:56s:185ms.
[15:09:09 INF] Starting CertificateCollector.
[15:09:09 INF] Completed CertificateCollector in 00h:00m:00s:302ms.
[15:09:09 INF] Starting FirewallCollector.
[15:09:10 INF] Completed FirewallCollector in 00h:00m:00s:653ms.
[15:09:10 INF] Starting ComObjectCollector.
[15:09:18 INF] Completed ComObjectCollector in 00h:00m:08s:707ms.
[15:09:18 INF] Starting EventLogCollector.
[15:09:26 INF] Completed EventLogCollector in 00h:00m:07s:491ms.
PS H:\VenusF\TOOLS\Attack Surface Analyzer MS\Asa-win-2.1.30-beta\res> .\asa.exe export-collect
[15:11:53 INF] AttackSurfaceAnalyzer v.2.1.30-beta+2c1f3fdf10
[15:11:54 INF] Comparing 1stScan vs 2ndScan.
[15:12:14 INF] Completed Comparing in 00h:00m:20s:382ms.
[15:12:14 INF] Loaded Analyses from Embedded.
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.CompareRuns(CompareCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 1036
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunExportCollectCommand(ExportCollectCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 518
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.<>c.<Main>b__7_2(ExportCollectCommandOptions opts) in D:\a\1\s\Asa\Program.cs:line 288
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 notParsedFunc)
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.Main(String[] args) in D:\a\1\s\Asa\Program.cs:line 284

**Comment by gfs** [comment]
Thanks for the detailed report.

Did you compile the code yourself to hit this or was it a release package?

-------- Original Message --------

**Comment by exquirentibus** [comment]
I downloaded the Asa-win-2.1.30-beta.zip release at 1:20pm 11/5/19.

**Comment by gfs** [comment]
Thanks again for the report.  I'm able to repro this. I should have a fix in the next day or two.
