### ISSUE TITLE
UserAccountCollector crash on clean Ubuntu 18.04

### ISSUE THREAD

**Issue by yitam** [microsoft/AttackSurfaceAnalyzer#339]
Failed to run ASA in a clean Ubuntu 18.04

1. Downloaded the latest version for Linux, v2.1.51
2. Ran `sudo ./AsaLaunch.sh collect -a`
3. A bunch of errors showed up (see below).
4. Re-ran step 2. The process hung for few minutes and then the same errors appeared.

Side note: when doing the same in Mojave, the process hung in step 2.

```
jennyt@jennyt:~/Asa-linux-2.1.51$ sudo ./AsaLaunch.sh collect -a
[10:25:25 INF] AttackSurfaceAnalyzer v.2.1.51+ccc428f205
[10:25:25 INF] Loaded filters: Embedded
[10:25:25 INF] Begin 2020-01-06T10:25:25.5794642-08:00.
[10:25:25 INF] Starting 8 Collectors.
[10:25:25 INF] Starting FileSystemCollector.
[10:25:25 INF] Scanning root /
[10:30:44 INF] Completed FileSystemCollector in 00h:05m:18s:453ms.
[10:30:50 INF] Completed FileSystemCollector in 00h:05m:24s:487ms.
[10:30:50 INF] Starting OpenPortCollector.
[10:30:50 INF] Completed OpenPortCollector in 00h:00m:00s:095ms.
[10:30:51 INF] Completed OpenPortCollector in 00h:00m:01s:096ms.
[10:30:51 INF] Starting ServiceCollector.
[10:30:51 INF] Completed ServiceCollector in 00h:00m:00s:014ms.
[10:30:52 INF] Completed ServiceCollector in 00h:00m:01s:017ms.
[10:30:52 INF] Starting UserAccountCollector.
[10:30:52 ERR] Error collecting from 'grep '^sudo:.*$' /etc/group | cut - d: -f4' finished with exit code = 2: grep: 4: No such file or directory

Std output:


:    at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String filename, String arguments) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 91
   at AttackSurfaceAnalyzer.Collectors.UserAccountCollector.ExecuteLinux() in /home/vsts/work/1/s/Lib/Collectors/UserAccountCollector.cs:line 255
   at AttackSurfaceAnalyzer.Collectors.UserAccountCollector.ExecuteInternal() in /home/vsts/work/1/s/Lib/Collectors/UserAccountCollector.cs:line 46
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/BaseCollector.cs:line 39
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Asa/Program.cs:line 1411 {3}
System.Runtime.InteropServices.ExternalException (0x80004005): 'grep '^sudo:.*$' /etc/group | cut - d: -f4' finished with exit code = 2: grep: 4: No such file or directory

Std output:



   at AttackSurfaceAnalyzer.Utils.ExternalCommandRunner.RunExternalCommand(String filename, String arguments) in /home/vsts/work/1/s/Lib/Utils/ExternalCommandRunner.cs:line 91
   at AttackSurfaceAnalyzer.Collectors.UserAccountCollector.ExecuteLinux() in /home/vsts/work/1/s/Lib/Collectors/UserAccountCollector.cs:line 255
   at AttackSurfaceAnalyzer.Collectors.UserAccountCollector.ExecuteInternal() in /home/vsts/work/1/s/Lib/Collectors/UserAccountCollector.cs:line 46
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute() in /home/vsts/work/1/s/Lib/Collectors/BaseCollector.cs:line 39
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(CollectCommandOptions opts) in /home/vsts/work/1/s/Asa/Program.cs:line 1411
[10:30:52 INF] Starting CertificateCollector.
[10:30:52 INF] Completed CertificateCollector in 00h:00m:00s:079ms.
[10:30:53 INF] Completed CertificateCollector in 00h:00m:01s:082ms.
[10:30:53 INF] Starting FirewallCollector.
[10:30:53 INF] Completed FirewallCollector in 00h:00m:00s:096ms.
[10:30:54 INF] Completed FirewallCollector in 00h:00m:01s:098ms.
[10:30:54 WRN] AttackSurfaceAnalyzer.Collectors.ComObjectCollector isn't compatible with this platform and has been skipped.
[10:30:54 INF] Starting EventLogCollector.
[10:30:54 INF] Completed EventLogCollector in 00h:00m:00s:043ms.
[10:30:55 INF] Completed EventLogCollector in 00h:00m:01s:058ms.
```

**Comment by gfs** [comment]
Can you check if the file '/etc/groups' exists on your Ubuntu system?

Which collector did the runs stall on?

-------- Original Message --------

**Comment by yitam** [comment]
hi @gfs

```
ls: cannot access '/etc/groups': No such file or directory
```

in mac mojave, it stalled at this step `Scanning root /`

**Comment by gfs** [comment]
Thanks.

/Etc/groups being missing is unexpected. I'll get a fresh install of Ubuntu and try again.

I was able to do a full run on my Mac system without stalling. Ill send you instructions for how to help narrow down what files it's getting stuck on (which should help me determine why) later today.

-------- Original Message --------

**Comment by gfs** [comment]
What is the output if you just run "groups"?

-------- Original Message --------

**Comment by yitam** [comment]
```
jennyt@jennyt:~$ groups
jennyt adm cdrom sudo dip plugdev lpadmin sambashare
```

**Comment by gfs** [comment]
Thanks. That's very strange. The /etc/groups file should be present on every POSIX system.

I'll try to write a workaround that uses the groups command instead since that seems to still work.

-------- Original Message --------

**Comment by yitam** [comment]
@gfs did you actually mean `/etc/group` file ?

**Comment by gfs** [comment]
Definitely possible. If that exists o think that's a typo in the code.

-------- Original Message --------

**Comment by scovetta** [comment]
Here's a trace of the *groups* command on Ubuntu 18.04. It definitely wants /etc/group.
```
miscovet@MISCOVET-DARTAN:/mnt/c/Users/miscovet$ strace groups 2>&1 | grep group
execve("/usr/bin/groups", ["groups"], [/* 18 vars */]) = 0
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
getgroups(0, NULL)                      = 12
getgroups(12, [4, 20, 24, 25, 27, 29, 30, 44, 46, 109, 110, 1000]) = 12
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 3
exit_group(0)                           = ?
```

Separately though, UserAccountCollector.cs:255 looks like it had an extra space after the hyphen in the `cut - d: -f4` command.

And probably no impact, but on line 265, I think it should be `username` instead of `"username"` - it doesn't look like you use groupsRaw in the Linux processor.

**Comment by yitam** [comment]
I might as well add that if the tarballs for Linux or macOS are downloaded using wget or curl, it seems that they can not be extracted using the `tar -xf` in a command line. 

But if I downloaded them manually from a web browser then it's fine. I wonder why.

**Comment by gfs** [comment]
Does the /etc/group file exist? I just double checked the code and that's the one we're checking.

**Comment by yitam** [comment]
yes it does

**Comment by scovetta** [comment]
That's really strange -- wget works fine for me:
```
$ wget 'https://github.com/microsoft/AttackSurfaceAnalyzer/releases/download/v2.1.51%2Bccc428f205/Asa-linux-2.1.51.tar.gz'
$ shasum Asa-linux-2.1.51.tar.gz
a5a634f4c2e6e9e30cd26ffad7e04c1aeeb1251a  Asa-linux-2.1.51.tar.gz
```
and tar -xf Asa-linux-2.1.51.tar.gz works fine.

For curl, you need to use -L to follow redirects, but wget should do that by default.

What was the full wget command you used?

**Comment by scovetta** [comment]
@gfs I think the problem wasn't /etc/group missing, it was a typo in the cut command. Fixed in #340 (I think).

**Comment by gfs** [comment]
> 
> 
> @gfs I think the problem wasn't /etc/group missing, it was a typo in the cut command. Fixed in #340 (I think).

Thanks. That fix looks right to me.

**Comment by yitam** [comment]
> That's really strange -- wget works fine for me:

wget works this time... when I tried it two weeks ago it didn't work back then. Thanks anyway!

**Comment by gfs** [comment]
I just pushed a new version to Release/2.1 so there should be a new build out shortly. (Should be 2.1.52)

Using that build, for your second issue (stalling on OS X) I'm adding an additional verbose logging statement.  If you run:

`sudo asa collect --parallelization false -f --verbose`

and it stalls it should end on a logging statement like:

`Started parsing C:\File\Name`

I'm interested in what file it stalls on.  The previous fix I made should have covered cases like pipes and sockets, but my suspicion is that I didn't catch all cases.

**Comment by gfs** [comment]
2.1.52 is ready for testing on OS X but Ubuntu needs another fix.

**Comment by gfs** [comment]
2.1.53 fixes the user account collector on Linux.  Thank you for your reports.  Please open a new issue to track the stalling on OS X if you're still encountering it in 2.1.53.

**Comment by yitam** [comment]
Yes @gfs I've confirmed that the problem in Ubuntu 18.04 has been fixed! 
Unfortunately, when I tried to run the latest in my mac mini (Catalina, not a VM this time), it crashed and caused my mac mini to reboot... I'll try again in a Mojave vm

**Comment by gfs** [comment]
> Yes @gfs I've confirmed that the problem in Ubuntu 18.04 has been fixed!

Great!

> Unfortunately, when I tried to run the latest in my mac mini (Catalina, not a VM this time), it crashed 

This is expected.  You won't be able to use the binaries from GitHub on Catalina because we haven't gotten our notarization pipeline working yet and MacOS Catalina now requires all foreign binaries to be [notarized](https://developer.apple.com/news/?id=10032019a). #341.

> and caused my mac mini to reboot... 

That definitely shouldn't have happened.  What step was it at when it crashed?  Right away? Are you building from source?

**Comment by yitam** [comment]
Never mind @gfs I re-ran asa in mojave but this time, rather than collecting all, I skipped some collectors. 

I believe the major issue was that the FileSystemCollector was taking **forever** to read every single file in `Applications`... and this is why it appears stalling (I quit after about an hour or so).

**Comment by gfs** [comment]
> I believe the major issue was that the FileSystemCollector was taking forever to read every single file in Applications... and this is why it appears stalling (I quit after about an hour or so).

If you have a lot of files the File collector can definitely take a long time.  If there are directories you don't care about (or ones you specifically care about) you can define them using the filters.json file or using the `--directories` argument.

If you do suspect that it is getting stuck you can run `sudo asa collect --parallelization false -f --verbose`, this will be even slower than a normal collection, but will identify exactly where it gets stuck.  If it is getting stuck and not just taking a while to complete, I'd be interested in where it is getting stuck as I can no longer repro that on my machines.

**Comment by yitam** [comment]
@gfs, initially I thought it was stuck so I did try tracing what it was collecting, as per your suggestion, but as far as I could see, it was essentially crawling through all files in Applications.

**Comment by gfs** [comment]
@yitam Thanks for the confirmation.  The file collector is a long running process, particularly if you have a slower machine (or VM) or a large number of files.
