### ISSUE TITLE
Microsoft.Data.Sqlite InvalidOperationException

### ISSUE THREAD

**Issue by xxnbyy** [microsoft/AttackSurfaceAnalyzer#358]
![image](https://user-images.githubusercontent.com/20261647/75621712-c84d7280-5bd2-11ea-8498-8ca6220e4344.png)

[15:31:06 INF] Loaded filters: Embedded
[15:31:06 INF] Begin ?20?/?03?/?01? ?15?:?31?:?02.
[15:31:06 INF] Starting 9 Collectors.
[15:31:06 INF] Starting FileSystemCollector.
[15:31:06 INF] Scanning root C:\
Unhandled exception. System.InvalidOperationException: This SqliteTransaction h
s completed; it is no longer usable.
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavio
)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.WriteNext()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.SleepAndFlushQueue()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.KeepSleepAndFlushQueue()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.<>c.<Setup>b__63_1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread th
eadPoolThread, ExecutionContext executionContext, ContextCallback callback, Obj
ct state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread th
eadPoolThread, ExecutionContext executionContext, ContextCallback callback, Obj
ct state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot,
Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.<>c.<<Setup>b__63_0>d.MoveNex
()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by gfs** [comment]
Sorry you're having trouble.

What version of Windows are you running on? I notice that the timestamp isn't printing properly.

How long after starting your run did the crash happen? I haven't been able to reproduce this.

-------- Original Message --------

**Comment by xxnbyy** [comment]
My windows version is windows 2012 r2 datacenter,and my system time is in GTM+8，the crash happen about 20 seconds after starting my run

**Comment by gfs** [comment]
Thanks.

I'm pushing a new version that uses a different SQLite library.  The build is running now and it should be available shortly (it should be 2.1.79).  I am hoping that addresses this issue.  I've seen something similar when running a version of windows that was outside of support.  However, .NET Core should support 2012 R2.

If the updated version doesn't fix it let me know and I'll set up a 2012 r2 system to test.

**Comment by xxnbyy** [comment]
there is another error on it.

[13:26:44 INF] This application collects usage data to help us improve Attack Su
rface Analyzer.
[13:26:44 INF] For our privacy policy visit: https://github.com/Microsoft/Attack
SurfaceAnalyzer/blob/master/PRIVACY.md.
[13:26:44 INF] To disable telemetry run Attack Surface Analyzer with these argum
ents: 'config --telemetry-opt-out true'.
[13:26:44 INF] Loaded filters: Embedded
[13:26:44 INF] Begin ?20?/?03?/?04? ?13?:?26?:?43.
[13:26:44 INF] Starting 9 Collectors.
[13:26:44 INF] Starting FileSystemCollector.
[13:26:45 INF] Scanning root C:\
[13:36:15 ERR] Error collecting from FileSystemCollector: unknown error
No transaction is active on this connection    at System.Data.SQLite.SQLiteTrans
actionBase.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransaction.Commit()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.Commit()
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute()
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(Collec
tCommandOptions opts)
[13:40:26 INF] Starting OpenPortCollector.
[13:40:26 WRN] Primary Parsing error when processing netstat.exe output: 协议
本地地址          外部地址        状态           PID
[13:40:32 ERR] Error collecting from OpenPortCollector: unknown error
No transaction is active on this connection    at System.Data.SQLite.SQLiteTrans
actionBase.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransaction.Commit()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.Commit()
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute()
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(Collec
tCommandOptions opts)
[13:40:32 INF] Starting ServiceCollector.
[13:40:32 ERR] Error collecting from ServiceCollector: 找不到     at System.Mana
gement.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.PropertyData.RefreshPropertyInfo()
   at System.Management.PropertyData..ctor(ManagementBaseObject parent, String p
ropName)
   at System.Management.PropertyDataCollection.get_Item(String propertyName)
   at System.Management.ManagementBaseObject.GetPropertyValue(String propertyNam
e)
   at AttackSurfaceAnalyzer.Collectors.ServiceCollector.ExecuteWindows()
   at AttackSurfaceAnalyzer.Collectors.ServiceCollector.ExecuteInternal()
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute()
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(Collec
tCommandOptions opts)
[13:40:32 INF] Starting UserAccountCollector.
[13:40:34 ERR] Error collecting from UserAccountCollector: unknown error
No transaction is active on this connection    at System.Data.SQLite.SQLiteTrans
actionBase.IsValid(Boolean throwError)
   at System.Data.SQLite.SQLiteTransaction.Commit()
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.Commit()
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.Execute()
   at AttackSurfaceAnalyzer.AttackSurfaceAnalyzerClient.RunCollectCommand(Collec
tCommandOptions opts)
[13:40:34 INF] Starting RegistryCollector.

**Comment by gfs** [comment]
Thanks.  I'll have to set up a server 2012 instance to attempt to replicate this.  I can't provide an ETA yet on a fix.

**Comment by gfs** [comment]
I have set up a fresh Server 2012 R2 Datacenter install and cannot reproduce this, I'm also not seeing the strange behavior in the timestamp.  I think there may be some issue with your Windows installation.

```
PS C:\Users\Administrator\Desktop\Asa-win-2.1.80> asa\Asa.exe collect -a
[11:07:58 INF] AttackSurfaceAnalyzer v.2.1.80+5fab4afaf9
[11:07:59 INF] Loaded filters: Embedded
[11:07:59 INF] Begin 2020-03-07T11:07:58.9466039-08:00.
[11:07:59 INF] Starting 9 Collectors.
[11:07:59 INF] Starting FileSystemCollector.
[11:07:59 INF] Scanning root C:\
[11:08:49 INF] Completed FileSystemCollector in 00h:00m:50s:272ms.
[11:08:49 INF] Starting OpenPortCollector.
[11:08:50 INF] Completed OpenPortCollector in 00h:00m:01s:118ms.
[11:08:50 INF] Starting ServiceCollector.
[11:08:50 WRN] AttackSurfaceAnalyzer.Collectors.ServiceCollector isn't supported on this platform and failed to run. Thi
s won't impact results for other collectors.
[11:08:50 INF] Completed ServiceCollector in 00h:00m:00s:036ms.
[11:08:50 INF] Starting UserAccountCollector.
[11:08:50 WRN] AttackSurfaceAnalyzer.Collectors.UserAccountCollector isn't supported on this platform and failed to run.
 This won't impact results for other collectors.
[11:08:50 INF] Completed UserAccountCollector in 00h:00m:00s:062ms.
[11:08:50 INF] Starting RegistryCollector.
[11:10:47 INF] Completed RegistryCollector in 00h:01m:57s:258ms.
[11:10:47 INF] Starting CertificateCollector.
[11:10:48 INF] Completed CertificateCollector in 00h:00m:01s:029ms.
[11:10:48 INF] Starting FirewallCollector.
[11:10:49 INF] Completed FirewallCollector in 00h:00m:01s:076ms.
[11:10:49 INF] Starting ComObjectCollector.
[11:10:57 INF] Completed ComObjectCollector in 00h:00m:07s:759ms.
[11:10:57 INF] Starting EventLogCollector.
[11:10:58 INF] Completed EventLogCollector in 00h:00m:01s:117ms.
PS C:\Users\Administrator\Desktop\Asa-win-2.1.80> asa\Asa.exe collect -a
[11:11:04 INF] AttackSurfaceAnalyzer v.2.1.80+5fab4afaf9
[11:11:04 INF] Loaded filters: Embedded
[11:11:04 INF] Begin 2020-03-07T11:11:04.5139898-08:00.
[11:11:04 INF] Starting 9 Collectors.
[11:11:04 INF] Starting FileSystemCollector.
[11:11:04 INF] Scanning root C:\
[11:11:48 INF] Completed FileSystemCollector in 00h:00m:44s:278ms.
[11:11:48 INF] Starting OpenPortCollector.
[11:11:50 INF] Completed OpenPortCollector in 00h:00m:01s:128ms.
[11:11:50 INF] Starting ServiceCollector.
[11:11:50 WRN] AttackSurfaceAnalyzer.Collectors.ServiceCollector isn't supported on this platform and failed to run. Thi
s won't impact results for other collectors.
[11:11:50 INF] Completed ServiceCollector in 00h:00m:00s:047ms.
[11:11:50 INF] Starting UserAccountCollector.
[11:11:50 WRN] AttackSurfaceAnalyzer.Collectors.UserAccountCollector isn't supported on this platform and failed to run.
 This won't impact results for other collectors.
[11:11:50 INF] Completed UserAccountCollector in 00h:00m:00s:089ms.
[11:11:50 INF] Starting RegistryCollector.
[11:13:50 INF] Completed RegistryCollector in 00h:02m:00s:325ms.
[11:13:50 INF] Starting CertificateCollector.
[11:13:51 INF] Completed CertificateCollector in 00h:00m:01s:020ms.
[11:13:51 INF] Starting FirewallCollector.
[11:13:52 INF] Completed FirewallCollector in 00h:00m:01s:076ms.
[11:13:52 INF] Starting ComObjectCollector.
[11:14:00 INF] Completed ComObjectCollector in 00h:00m:08s:043ms.
[11:14:00 INF] Starting EventLogCollector.
[11:14:01 INF] Completed EventLogCollector in 00h:00m:01s:094ms.
PS C:\Users\Administrator\Desktop\Asa-win-2.1.80> asa\Asa.exe export-collect
[11:14:21 INF] AttackSurfaceAnalyzer v.2.1.80+5fab4afaf9
[11:14:21 INF] Comparing 2020-03-07T11:07:58.9466039-08:00 vs 2020-03-07T11:11:04.5139898-08:00.
[11:14:47 INF] Completed Comparing in 00h:00m:25s:566ms.
[11:14:47 INF] Loaded Analyses from Embedded.
[11:14:47 INF] Completed Analysis in 00h:00m:00s:160ms.
[11:14:47 INF] Completed Flushing in 00h:00m:00s:000ms.
[11:14:48 INF] Output written to: C:\Users\Administrator\Desktop\Asa-win-2.1.80\2020-03-07T11_07_58.9466039-08_00_vs_202
0-03-07T11_11_04.5139898-08_00_summary.json.txt
```

**Comment by xxnbyy** [comment]
So, is there any solutions to resolve this problem?I install an exchange 2013 on it and open the Activedirectory on it.

**Comment by gfs** [comment]
Unfortunately since I'm unable to reproduce this I'm unable to provide a solution. I believe this is an issue with your system not an issue with Attack Surface analyzer. 

My recommendation would be to try a fresh installation of a fully up to date 2012 R2.

**Comment by xxnbyy** [comment]
ok,thx
