### ISSUE TITLE
Fatal error occured while scanning disk on windows

### ISSUE THREAD

**Issue by FurryAcetylCoA** [microsoft/AttackSurfaceAnalyzer#535]
**Describe the bug**
An fatal error occured while FileSystemCollector scanning a disk
**To Reproduce**
1. Use `asa gui` to start the program
2. Keep everything default and click 'Get Started'
3. Click 'Collect Data' (still keep everything default)
4. Wait for a while
5. See error

**Screenshots**
```
[21:24:57 INF] AttackSurfaceAnalyzer v.2.2.57+7af37f8172
Hosting environment: Production
Content root path: C:\Users\**MY_USERNAME**\Desktop\windows\Cli
Now listening on: http://127.0.0.1:5000
Application started. Press Ctrl+C to shut down.
[21:25:10 INF] Begin 20/08/27 下午9:25:05.
[21:25:10 INF] Starting 9 Collectors.
[21:25:10 INF] Starting FileSystemCollector.
[21:25:10 INF] Scanning root B:\
[21:25:51 INF] Scanning root C:\
[21:32:24 INF] Scanning root D:\
[21:54:10 INF] Scanning root E:\
[22:20:33 INF] Scanning root F:\
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Buffer.Memmove(Byte*, Byte*, UInt64)
   at System.Runtime.InteropServices.SafeBuffer.ReadArray[[System.Byte, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](UInt64, Byte[], Int32, Int32)
   at System.IO.UnmanagedMemoryAccessor.ReadArray[[System.Byte, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int64, Byte[], Int32, Int32)
   at PeNet.FileParser.MMFile.ToArray()
   at PeNet.Header.Authenticode.AuthenticodeInfo.ComputeAuthenticodeHashFromPeFile(System.Security.Cryptography.HashAlgorithm)
   at PeNet.Header.Authenticode.AuthenticodeInfo.VerifyHash()
   at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
   at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
   at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.FilePathToFileSystemObject(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.<ExecuteInternal>g__TryIterateOnDirectory|9_0(System.String)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass44_0`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<PartitionerForEachWorker>b__1(System.Collections.IEnumerator ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 2004  (19041.450)
 - Application Version: v. 2.2.57+7af37f8172 
 - CLI or GUI: GUI

**Additional Context**
Info about disk F:
* sata SSD
* NTFS
* Capacity 112GB （95.5GB used）
* F: is the only volume on that Physical disk

**Comment by gfs** [comment]
Thanks for your report.  

This is a repro of this issue: https://github.com/dotnet/runtime/issues/38218, which is actually an issue in PeNet.  I've opened a new issue here: https://github.com/secana/PeNet/issues/165.

It would help debug if we had the file that caused the crash.  It will be an executable or assembly of some kind.

If you run `asa collect -f --directories F:\ --verbose --singlethread` it should print the name of each file as it processes it and the culprit should be the one right before the crash.

If you can't reproduce the crash that might also be useful information.

**Comment by gfs** [comment]
I believe this issue is fixed in the latest PeNet.  I just pushed a commit to bump the dependencies which should kick off the build.

Please try 2.2.58 and let me know if that fixes your issue.

**Comment by gfs** [comment]
Encountering an issue with the build pipeline.  Should have an update out later today.

**Comment by FurryAcetylCoA** [comment]
I build the new version myself and the problem are all gone. I believe this bug is fixed.

By the way. The verbose mode indicate that ASA(old version) crushed while processing Destiny2.exe (an online game). I believe this has something to do with the anti-cheat protections.

Closing this issue
