### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by mhbosch** [microsoft/AttackSurfaceAnalyzer#560]
**Describe the bug**
Abort with Message

**To Reproduce**
run asa collect -a

**Expected behavior**

**Screenshots**
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Span`1[[System.Byte, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
   at PeNet.Header.Authenticode.ContentInfo..ctor(System.Span`1<Byte>)
   at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
   at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
   at PeNet.PeFile.get_Authenticode()
   at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.FilePathToFileSystemObject(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.<ExecuteInternal>g__TryIterateOnDirectory|9_0(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.<ExecuteInternal>b__9_5(System.String)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass44_0`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<PartitionerForEachWorker>b__1(System.Collections.IEnumerator ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecuteAction(Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**System Configuration (please complete the following information):**
Windows 10 Pro
19042.360

**Additional Context**

**Comment by gfs** [comment]
Thanks for your report.  What version of Attack Surface Analyzer are you running?

This has been an issue in the past with a known cause in PENet before which we've addressed.  If you can run collect with `--single-thread --verbose` it should print the name of the file right before the crash.  Identifying that file will help us solve the issue.

If you are experiencing this on the latest version of Attack Surface Analyzer we will need additional information about the file which causes the crash to investigate further.

**Comment by mhbosch** [comment]
Hello,

im using AttackSurfaceAnalyzer v.2.2.74+efd3bdfa22
Asa 2.2.74+efd3bdfa22

This are the last Information. 

[00:20:13 VRB] Started parsing C:\Program Files\EaseUS\EaseUS Data Recovery Wizard\DRWUI.exe
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UInt64)
   at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
   at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
   at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.FilePathToFileSystemObject(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.<ExecuteInternal>g__TryIterateOnDirectory|9_0(System.String)
   at AttackSurfaceAnalyzer.Collectors.FileSystemCollector.ExecuteInternal()
   at AttackSurfaceAnalyzer.Collectors.BaseCollector.TryExecute()
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.RunCollectCommand(AttackSurfaceAnalyzer.CollectCommandOptions)
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient+<>c.<Main>b__4_0(AttackSurfaceAnalyzer.CollectCommandOptions)
   at CommandLine.ParserResultExtensions.MapResult[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](CommandLine.ParserResult`1<System.Object>, System.Func`2<System.__Canon,Int32>, System.Func`2<System.__Canon,Int32>, System.Func`2<System.__Canon,Int32>, System.Func`2<System.__Canon,Int32>, System.Func`2<System.__Canon,Int32>, System.Func`2<System.__Canon,Int32>, System.Func`2<System.__Canon,Int32>, System.Func`2<System.Collections.Generic.IEnumerable`1<CommandLine.Error>,Int32>)
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.Main(System.String[])

**Comment by gfs** [comment]
Thanks @mhbosch. If you could provide that file that would be the fastest way for me to resolve this with the PENet Developer.  Otherwise I will try to take some time this week to install and validate against EaseUs.

**Comment by mhbosch** [comment]
How can i provide the File?

**Comment by gfs** [comment]
I believe you can zip it and attach it to a comment here.

-------- Original Message --------

**Comment by gfs** [comment]
Thanks. I'll take a look today and forward to the PENet team if appropriate.

-------- Original Message --------

**Comment by gfs** [comment]
This looks like this is an issue with our PE Net dependency, see the referenced bug to track the issue further.  They have previously been very responsive when we encounter issues with unique binaries so hopefully we will have a fix soon.

Because of the way the error propagates we can't just catch it unfortunately.

In the interim you can use the `--skip-directories` argument to skip the directory containing this binary so you can complete the rest of your scan.

**Comment by mhbosch** [comment]
First, i updated the Software to the actual Version. This skip the error.

**Comment by gfs** [comment]
Glad to hear that you are no longer having the issue.  Thanks for all your detail.

I'll keep this open to track the needed update to the PE Net dependency to handle the provided file.

**Comment by ragolsec** [comment]
Hi,
I'm experiencing the same issue. 

"Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UInt64)
   at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
   at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
   at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)
......
"

Thanks for the help above, I've narrowed down the issue to a specific file. Unfortunately I can't provide that file for analysis, at least not yet. 

Is there something else I could test to further analyze the situation? This is a signed dll. Can the signing cause issues, so if I'll replace the signed dll with unsigned one, can it help?

**Comment by ragolsec** [comment]
Hi, tested the following changes to the problematic file and still the same crash happens. 

Directly self compiled without signing and setting metadata / file properties.

**Comment by gfs** [comment]
Thanks for the additional details. I've filed a bug with PENet and will investigate further this week.

-------- Original Message --------

**Comment by gfs** [comment]
This should be fixed with #563 based on the initial file for this bug.  @ragolsec if your test file still fails with the new version (should be live in 20-30 minutes) we would need the file to be able to identify why it is failing.

**Comment by ragolsec** [comment]
Seems to have fixed also the issue I was seeing. 

Thanks for quick response!
