### ISSUE TITLE
Exception when running asa export-collect

### ISSUE THREAD

**Issue by masty1982** [microsoft/AttackSurfaceAnalyzer#576]
**Describe the bug**
AggregateException/NullReferenceException thrown when running 'asa export-collect --analyze'.

**To Reproduce**
PS C:\Users\masty\Downloads\ProductX> asa export-collect --analyze
[16:47:33 INF] AttackSurfaceAnalyzer v.2.2.76+68c0dfa092
[16:47:34 INF] Provided null run Ids using latest two runs.
[16:47:34 INF] Comparing baseline vs ProductX.
[16:47:45 INF] Completed Comparing in 00h:00m:10s:917ms.
[16:47:45 INF] Loaded Analyses from Embedded.
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.<>c__DisplayClass19_0.<CompareRuns>b__0(CompareResult res) in D:\a\1\s\Cli\Program.cs:line 704
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.CompareRuns(CompareCommandOptions opts) in D:\a\1\s\Cli\Program.cs:line 700
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.RunExportCollectCommand(ExportCollectCommandOptions opts) in D:\a\1\s\Cli\Program.cs:line 313
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.<>c.<Main>b__4_2(ExportCollectCommandOptions opts) in D:\a\1\s\Cli\Program.cs:line 75
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 notParsedFunc)
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.Main(String[] args) in D:\a\1\s\Cli\Program.cs:line 61

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version: Windows Server 2016
 - Application Version: v.2.2.76+68c0dfa092
 - CLI or GUI: CLI

**Additional Context**
If I run 'asa gui --verbose' and then run analysis in gui, then there are no problems (no error messages in the PS window and analysis is ok). I am getting same exception with different .sqlite files.

**Comment by gfs** [comment]
Thanks for your detailed report. I am glad you were able to use the GUI as a workaround. I’ll investigate this week.

**Comment by gfs** [comment]
After checking the behavior of the command line and the GUI I'm actually surprised that it worked one way but not the other. I have a potential fix in #577 and you can try with the new version after the merge.

**Comment by rein123** [comment]
This issue seems to be quite present now. Is there a new official release planned in the near future? Thx!

**Comment by gfs** [comment]
Hey @rein123 sorry this issue is still present. 

It should be fixed in the release/v2.2 branch if you build from source. We are currently experiencing an issue with our Build pipeline that is preventing new releases from being published.

**Comment by gfs** [comment]
The signing issue is still present but hopefully will be resolved this week @daalcant.

**Comment by daalcant** [comment]
@gfs @masty1982 @rein123 
The build pipeline is finally fixed! Release 2.2.78 is now available with the fix from #576 included.
https://github.com/microsoft/AttackSurfaceAnalyzer/releases/tag/v2.2.78
