### ISSUE TITLE
Your Bug Title Here

### ISSUE THREAD

**Issue by Heawen** [microsoft/AttackSurfaceAnalyzer#670]
Unable to run
```
E:\下载\Chrome浏览器下载\ASA_win_2.3.289>Asa.exe gui  
[15:33:14 INF] AttackSurfaceAnalyzer v.2.3.289+9dddb7f7a4                                                           
[15:33:15 INF] Running from E:\下载\Chrome浏览器下载\ASA_win_2.3.289   
[15:33:15 INF] App is at E:\下载\Chrome浏览器下载\ASA_win_2.3.289\Asa.dll   
Unhandled exception. System.IO.DirectoryNotFoundException: E:\staticwebassets\  
        at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters) 
        at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)   
        at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
        at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
        at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(WebApplicationOptions options)
        at Microsoft.CST.AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.RunGuiCommand(GuiCommandOptions opts) in D:\a\1\s\Cli\AttackSurfaceAnalyzerClient.cs:line 440   
        at Microsoft.CST.AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.<>c.<Main>b__9_6(GuiCommandOptions opts) in D:\a\1\s\Cli\AttackSurfaceAnalyzerClient.cs:line 116  
        at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 notParsedFunc)
        at Microsoft.CST.AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerClient.Main(String[] args) in D:\a\1\s\Cli\AttackSurfaceAnalyzerClient.cs:line 75 
```

**Screenshots**
![微信截图_20221108154546](https://user-images.githubusercontent.com/69815495/200504264-8181db9a-e5e1-4e8a-90eb-a1e20b07e2b5.png)

**System Configuration (please complete the following information):**
 - OS:   Windows 10
 - OS Version: 22H2
 - Application Version:  v.2.3.289+9dddb7f7a4

**Comment by gfs** [comment]
Thanks for the report. This is Fixed in 2.3.290.
