### ISSUE TITLE
Create DB as normal user before operating on it as admin

### ISSUE THREAD

**Issue by gfs** [Microsoft/AttackSurfaceAnalyzer#96]
Running non-elevated after running elevated on linux hits an exception

```
Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 8: 'attempt to write a readonly database'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.get_Transaction() in D:\a\1\s\Lib\Utils\DatabaseManager.cs:line 178
   at AttackSurfaceAnalyzer.Utils.DatabaseManager.Setup() in D:\a\1\s\Lib\Utils\DatabaseManager.cs:line 72
   at AttackSurfaceAnalyzer.Cli.AttackSurfaceAnalyzerCLI.Main(String[] args) in D:\a\1\s\Cli\Program.cs:line 212
```

It looks like we either need to create the database itself with non-admin permissions (preferred) or move the admin check earlier (easier).

**Comment by gfs** [comment]
I did some work to move the admin checks around and I think I covered the original proposal here to simply stop users from seeing this error.
